# Napisati program koji iscrtava formu za registraciju kao sa slike

print("*******************************************")
print("*                                         *")
print("*                Register                 *")
print("*             _________________________   *")
print("*  Email:    |                         |  *")
print("*             *************************   *")
print("*                                         *")
print("*             _________________________   *")
print("*  Password: |                       <>|  *")
print("*             *************************   *")
print("*                                         *")
print("*                                         *")
print("*  _                                      *")
print("* | | I Agree                             *")
print("*                                         *")
print("*                __________________       *")
print("*               |                  |      *")
print("*               |   Register       |      *")
print("*               |__________________|      *")
print("*                                         *")
print("*******************************************")
